---
- hosts: server
  gather_facts: no

  tasks:
    - name: Install java8
      become: yes
      apt:
        name: default-jre
        state: latest

    - name: Build the application
      run_once: true
      shell: ./scripts/build-server.sh
      delegate_to: 127.0.0.1

    - name: Create the play group
      become: yes
      group:
        name: play
        state: present

    - name: Create the play user
      become: yes
      user:
        name: play
        group: play
        state: present
        system: yes

    - name: Create the app directory
      become: yes
      file:
        path: /home/play/
        state: directory
        owner: play
        group: play

    - name: Upload the app
      become: yes
      copy:
        src: app.jar
        dest: /home/play/app.jar
        owner: play
        group: play

    - name: Set the application files permissions
      become: yes
      file:
        dest: /home/play/
        owner: play
        group: play
        recurse: yes

    - name: Add the systemd service
      become: yes
      copy:
        src: systemd-services/scammer-detector-bot.service
        dest: /etc/systemd/system/
        owner: root
        group: root

    - name: Pick up systemd changes
      become: yes
      systemd:
        daemon_reload: yes

    - name: Restart the application
      become: yes
      systemd:
        name: scammer-detector-bot
        state: restarted

    - name: Enable the application to run on system startup
      become: yes
      systemd:
        name: scammer-detector-bot
        enabled: yes
